logging:
  level:
    root: WARN
    hu.projects.expense_tracker: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate: OFF
    org.flywaydb: INFO

spring:
  datasource:
    url: jdbc:h2:mem:app-db
    username: app_user
    password: app_password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false