server:
  port: 8080


spring:
  profiles:
    active: dev
    default: production

  application:
    name: backend-api

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
