server:
  port: 8080

spring:
  profiles:
    active: dev
    default: production

  application:
    name: backend-api

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 20
        default-page-size: 5
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
